# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 07:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_No', models.CharField(max_length=20, unique=True)),
                ('bill_goods_name', models.CharField(max_length=20)),
                ('bill_goods_num', models.IntegerField()),
                ('bill_goods_money', models.FloatField()),
                ('bill_spend', models.BooleanField(default=True)),
                ('bill_goods_des', models.CharField(max_length=4000)),
                ('bill_finish_time', models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 15, 15, 4, 48, 688458))),
                ('bill_isDelete', models.BooleanField(default=False)),
            ],
            managers=[
                ('bill_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_No', models.IntegerField(unique=True)),
                ('supplier_info', models.CharField(max_length=20, null=True)),
                ('supplier_des', models.CharField(max_length=4000)),
                ('supplier_name', models.CharField(max_length=20, null=True)),
                ('supplier_phone', models.IntegerField()),
                ('supplier_address', models.CharField(max_length=4000)),
                ('supplier_isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': '_supplier',
                'ordering': ['id'],
            },
            managers=[
                ('supplier_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_No', models.IntegerField(unique=True)),
                ('user_name', models.CharField(max_length=20, null=True)),
                ('user_password', models.CharField(max_length=10, null=True)),
                ('user_gender', models.BooleanField(default=True)),
                ('user_age', models.IntegerField()),
                ('user_phone', models.IntegerField()),
                ('user_address', models.CharField(max_length=4000)),
                ('user_isDelete', models.BooleanField(default=False)),
                ('job_type', models.BooleanField(default=False)),
            ],
            options={
                'db_table': '_user',
                'ordering': ['id'],
            },
            managers=[
                ('user_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='bill_form',
            name='bill_goods_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markeysystem.Supplier_Form'),
        ),
    ]
