# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 07:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markeysystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_form',
            name='bill_finish_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 18, 15, 4, 55, 793539)),
        ),
    ]
