# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 11:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markeysystem', '0002_auto_20180618_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_form',
            name='bill_finish_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 18, 19, 34, 38, 53402)),
        ),
    ]
