# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 08:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_address', models.CharField(default=False, max_length=255)),
                ('address_name', models.CharField(max_length=20)),
                ('address_phone', models.IntegerField()),
                ('address_datetime', models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 20, 16, 58, 10, 851657))),
                ('address_isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Address',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_isDelete', models.BooleanField(default=False)),
                ('car_datetime', models.DateTimeField(default=datetime.datetime(2018, 6, 20, 16, 58, 10, 851657))),
            ],
            options={
                'db_table': 'Car',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_No', models.CharField(max_length=20, unique=True)),
                ('order_datetime', models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 20, 16, 58, 10, 852650))),
                ('order_isDelete', models.BooleanField(default=False)),
                ('order_address_foreignkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Freshmarket.Address')),
                ('order_car_foreignkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Freshmarket.Car')),
            ],
            options={
                'db_table': 'Order',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product_picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_name', models.CharField(max_length=50)),
                ('picture_icron', models.ImageField(upload_to='img/')),
                ('picture_type', models.IntegerField()),
                ('picture_datetime', models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 20, 16, 58, 10, 849626))),
                ('picture_isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Picture',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('product_num', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('product_desc', models.CharField(max_length=255)),
                ('product_crate_time', models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 20, 16, 58, 10, 849626))),
                ('product_isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Products',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_isDelete', models.BooleanField(default=False)),
                ('scan_datatime', models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 20, 16, 58, 10, 850659))),
                ('scan_foreignkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freshmarket.Products')),
            ],
            options={
                'db_table': 'Scan',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_phone', models.IntegerField()),
                ('user_address', models.CharField(max_length=255)),
                ('user_crate_time', models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 20, 16, 58, 10, 848628))),
                ('user_isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'User',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='product_picture',
            name='picture_foreKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freshmarket.Products'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_foreignkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freshmarket.Products'),
        ),
        migrations.AddField(
            model_name='address',
            name='address_foreignkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Freshmarket.User'),
        ),
    ]
