# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Freshmarket', '0010_auto_20180624_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 24, 18, 11, 48, 580638)),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 24, 18, 11, 48, 579637)),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_foreignkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freshmarket.Products', unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 24, 18, 11, 48, 580638)),
        ),
        migrations.AlterField(
            model_name='product_picture',
            name='picture_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 24, 18, 11, 48, 578643)),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_crate_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 24, 18, 11, 48, 578643)),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_datatime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 24, 18, 11, 48, 579637)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_crate_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 24, 18, 11, 48, 577651)),
        ),
    ]
