# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 06:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freshmarket', '0016_auto_20180625_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_car_foreignkey',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 25, 14, 29, 30, 233280)),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 25, 14, 29, 30, 233280)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 25, 14, 29, 30, 234277)),
        ),
        migrations.AlterField(
            model_name='order_products',
            name='op_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 25, 14, 29, 30, 234277)),
        ),
        migrations.AlterField(
            model_name='product_picture',
            name='picture_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 25, 14, 29, 30, 232282)),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_crate_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 25, 14, 29, 30, 231285)),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_datatime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 25, 14, 29, 30, 232282)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_crate_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 25, 14, 29, 30, 231285)),
        ),
    ]
