# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 08:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Freshmarket', '0026_auto_20180625_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_foreignkey',
            new_name='car_product_foreignkey',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_user',
            new_name='car_user_foreignkey',
        ),
        migrations.RenameField(
            model_name='order_products',
            old_name='op_foreignkey',
            new_name='op_order_foreignkey',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='scan_foreignkey',
            new_name='scan_products_foreignkey',
        ),
        migrations.AddField(
            model_name='order',
            name='order_user_foreignkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Freshmarket.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_products',
            name='op_user_foreignkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Freshmarket.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='scan_user_foreignkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Freshmarket.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='address_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 26, 16, 41, 38, 559647)),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 16, 41, 38, 558647)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 26, 16, 41, 38, 560642)),
        ),
        migrations.AlterField(
            model_name='product_picture',
            name='picture_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 26, 16, 41, 38, 557653)),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_crate_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 26, 16, 41, 38, 557653)),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_datatime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 26, 16, 41, 38, 558647)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_crate_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 26, 16, 41, 38, 556632)),
        ),
    ]
