# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 19:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Freshmarket', '0032_auto_20180627_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_middle_Op',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            managers=[
                ('omo_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrdPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orp_name', models.CharField(max_length=254)),
                ('orp_num', models.IntegerField()),
                ('orp_sing_price', models.FloatField()),
            ],
            options={
                'ordering': ['-id'],
            },
            managers=[
                ('orp_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='order_products',
            name='op_order_foreignkey',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 27, 3, 59, 2, 234304)),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 3, 59, 2, 234304)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 27, 3, 59, 2, 235300)),
        ),
        migrations.AlterField(
            model_name='product_picture',
            name='picture_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 27, 3, 59, 2, 232309)),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_crate_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 27, 3, 59, 2, 232309)),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_datatime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 27, 3, 59, 2, 233306)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_crate_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 27, 3, 59, 2, 231312)),
        ),
        migrations.AddField(
            model_name='ordpro',
            name='orp_order_foreignkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freshmarket.Order'),
        ),
        migrations.AddField(
            model_name='ordpro',
            name='orp_user_foreignkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freshmarket.User'),
        ),
        migrations.AddField(
            model_name='order_middle_op',
            name='omo_ordPro_foreignkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freshmarket.OrdPro'),
        ),
        migrations.AddField(
            model_name='order_middle_op',
            name='omo_order_foreignkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freshmarket.Order'),
        ),
    ]
